# Generated by Django 3.2.13 on 2022-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220517_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
